package-lock.json
package.json
src/manifest.json
src/pages/Background/index.js
src/pages/Content/content.styles.css
src/pages/Content/index.js
src/pages/Content/modules/Questionnaire.js
src/pages/Content/modules/StarRating.js
src/pages/Content/modules/questionarre.js

Created dynamic star rating and questionnaire which gets added to the bottom of the page when activate is pressed.

Created Questionnaire

---

backend/package.json

- Created a script in package.json to run the backend server

Create script to start backend server locally

---

backend/package-lock.json
package-lock.json
package.json

In order to make our testing easier between the mongo server and the frontend, I added a new script into the package.json.
Once you pull these new changes, run `npm i`
Now, if you want to run the backend and the front end at SAME TIME use `npm run dev`

Added new script to package.json

---

src/manifest.json
src/pages/Background/index.js
src/pages/Content/index.js
src/pages/Content/modules/Questionnaire.js

On submitting the questionnaire the currently signed-in user's email and id are logged to the console with no need for additional sign-in. This uses the identity.email and identity permissions.

User authentication

---

.gitignore
backend/index.js
backend/package-lock.json
backend/package.json
backend/route.rest
package-lock.json
package.json
src/pages/Content/index.js
src/pages/Content/modules/Questionnaire.js
src/pages/Content/modules/StarRating.js
src/pages/Content/modules/print.js

- Fixed questionnaire submit button (We would just need to implement the backend and Cooper's algorithm)
- Added state to questionnaire.js
- Made StarRating component use a prop
- Added dotenv
- Removed mongoDB uri from appearing in repo
In order to fix go forward on testing for mongoDB, create a .env file in the root folder and  paste `MONGODB_URI={your mongo uri here}` into it.
Questionnaire 
Result of submit button

Questionnaire update and security fixes

---

src/manifest.json
src/pages/Background/index.js
src/pages/Background/workingUrls.js
src/pages/Content/index.js

I created a parse for urls and cleaned up the activate button so it worked cleaner without messing up stuff. Then I placed the questionnaires where they needed to go for the 7 sites in the zenhub Medium, NY times, CNN, Fox, Verge, Vox and Wired.

Questionnaire placement

---

src/containers/Score/Score.js

Just the score file, thought I pulled the most recent main but my git was acting weird.(shouldn't matter) Just put it in a random folder, can decide later where it's best located

Score page framework

---

src/pages/Popup/Popup.css
src/pages/Popup/Popup.jsx
src/pages/Popup/modules/StarRating.js

https://user-images.githubusercontent.com/21961090/109263610-88af6b80-77d1-11eb-98d4-6a03502b9a86.mov

Added reliability score to popup

---

backend/routes/reviewRouter.js

Updated response

---

src/pages/Background/index.js
src/pages/Content/index.js

standardized axios post requests calls to use axios.post and fixed but with not saving new website

Minorfixes

---

env
src/pages/Content/content.styles.css
src/pages/Content/index.js
src/pages/Content/modules/Questionnaire.js
src/pages/Content/modules/StarRating.js

1. The questionnaire properly waits for the DB to respond before showing the user the result
2. All questions must be answered before submitting the questionnaire
3. If a question is changed the submit button reappears (after first submit)
4. Button styling mimicking bootstrap without changing fonts

Questionnaire fine tuning

---

backend/routes/reviewsRouter.js
env
src/pages/Content/index.js
src/pages/Content/modules/Questionnaire.js
src/pages/Content/modules/StarRating.js
src/pages/Popup/Popup.jsx

1. The questionnaire now pulls your previous responses when a page you have submitted a questionnaire is revisited
2. Questionnaire placement bug fixed 
3. Unsupported site bug fixed
4. getReview route response fixed
5. popup reliability score NaN bug fixed

Questionnaire and stability fixes

---

src/pages/Content/index.js
src/pages/Popup/Popup.jsx
src/pages/Popup/modules/messenger.js

you can now for the most part with some exceptions get the first author name guaranteed from all the articles that have them and two authors from cnn and nytimes. But you still can't get 3 or more authors

Created get Author and fixed the messenger.jx in popup so that you can get the authors array

---

src/pages/Content/index.js
src/pages/Content/modules/Tooltip.js

The tooltip is working and now highlights
Before thursday, i'll definitely keep testing this.
**TO-DO**
Extension working on Vox article 
Extension working on Verge article
Extension working on Fox article

Tooltip added [TO-DO below]

---

package-lock.json
package.json
src/pages/Content/content.styles.css
src/pages/Content/index.js
src/pages/Content/modules/Comment-Component.js
src/pages/Content/modules/Comment-Container.js
src/pages/Content/modules/Comment-Scroll.js
src/pages/Content/modules/Linked-List.js

Added comment container functionality that allows comments to shift around to appropriate positions.
https://user-images.githubusercontent.com/21961090/113475389-626d9300-9443-11eb-93ab-327baf1321f9.mp4
sorry for the low res it wouldn't let me upload a larger filesize

Comment UI

---

src/pages/Content/content.styles.css
src/pages/Content/index.js
src/pages/Content/modules/Comment-Scroll.js
src/pages/Content/modules/Tooltip-Component.js

Finished Fixing tooltip and cleaning up animations

fixing-broken-tooltip

---

src/pages/Content/index.js
src/pages/Content/modules/Comment-Container.js
src/pages/Content/modules/Comment-Scroll.js

- Fixed issue with float to int conversion on height check that caused unwanted side effects 
- Added functionality that allows all comments to shift to their selection if they will not overlap

comment-scroll-bug-fixes

---

.gitignore
backend/Score/Score.js
backend/app.json
backend/index.js
backend/package-lock.json
backend/package.json
backend/procfile
backend/routes/siteRouter.js
package-lock.json
package.json
src/API/APIModule.js
src/pages/Background/index.js
src/pages/Content/Questionnaire.js
src/pages/Content/content.styles.css
src/pages/Content/index.js
src/pages/Content/modules/Questionnaire-Component.js
src/pages/Content/modules/Tooltip-Component.js
src/pages/Popup/Popup.jsx
src/pages/Popup/modules/PopupHelper.js
utils/webserver.js

- Added new scripts to package.json
- API is on Heroku and we can now test our extension using the live API
- Added an API module to avoid importing axios in multiple files, this module will take care of axios calls and switching environments between production and development
- Implemented the new API module in our index.js (no more long tedious axios calls)
If you want to test using the heroku API use `npm run prod`
If you want to test using a local server use `npm run dev`
Test before merging please!

API Changes

---

backend/routes/siteRouter.js
backend/routes/userRouter.js
src/API/APIModule.js

- Delete/Reply Comments added
- Deployed new routes to heroku
- Add/Edit notes (Check APIModules.js) all documentation is there
Try testing these on your branch first before merging @yasaad

Comments and notes basic functionality

---

backend/routes/userRouter.js
src/API/APIModule.js
src/pages/Content/index.js
src/pages/Content/modules/Container-Component.js
src/pages/Content/modules/Container-Scroll.js
src/pages/Content/modules/ContainerClass.js
src/pages/Content/modules/Note-Component.js

saves comments and notes to the backend. Gets them as well just need to serialize selection to visualize them.

Comment and note backend

---

backend/routes/siteRouter.js
backend/routes/userRouter.js
src/pages/Content/content.styles.css
src/pages/Content/index.js
src/pages/Content/modules/Activated-Component.js
src/pages/Content/modules/Comment-Component.js
src/pages/Content/modules/Container-Component.js
src/pages/Content/modules/Container-Scroll.js
src/pages/Content/modules/ContainerClass.js
src/pages/Content/modules/Note-Component.js

Fix multi note comment load
